#!/bin/sh
echo "config.plugins.subtitlesSupport.encodingsGroup=Arabic"
	echo "config.plugins.subtitlesSupport.external.font.size=52"
	echo "config.plugins.subtitlesSupport.search.edna_cz.enabled=False"
	echo "config.plugins.subtitlesSupport.search.itasa.enabled=False"
	echo "config.plugins.subtitlesSupport.search.lang1=ar"
	echo "config.plugins.subtitlesSupport.search.lang2=ar"
	echo "config.plugins.subtitlesSupport.search.lang3=ar"
	echo "config.plugins.subtitlesSupport.search.mysubs.enabled=False"
	echo "config.plugins.subtitlesSupport.search.opensubtitles.enabled=False"
	echo "config.plugins.subtitlesSupport.search.podnapisi.enabled=False"
	echo "config.plugins.subtitlesSupport.search.prijevodionline.enabled=False"
	echo "config.plugins.subtitlesSupport.search.serialzone_cz.enabled=False"
	echo "config.plugins.subtitlesSupport.search.subtitles_gr.enabled=False"
        echo "config.plugins.subtitlesSupport.search.subdl_com.enabled=False"
	echo "config.plugins.subtitlesSupport.search.subtitlist.enabled=False"
	echo "config.plugins.subtitlesSupport.search.titlovi.enabled=False"
	echo "config.plugins.subtitlesSupport.search.titulky_com.enabled=False"